# Generated by Django 3.2 on 2022-02-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Название наряда')),
                ('ratio', models.FloatField(default='', verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Наряд по',
                'verbose_name_plural': 'Наряд по',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Фамилия Имя')),
                ('rank', models.TextField(max_length=30, verbose_name='Звание')),
                ('number', models.TextField(max_length=30, verbose_name='Факультет')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Офицер',
                'verbose_name_plural': 'Офицеры',
            },
        ),
    ]
