# Generated by Django 3.2.8 on 2021-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Факультет')),
                ('descriptions', models.TextField(default='', max_length=100, verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField(verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Имя')),
                ('surname', models.TextField(default='', max_length=100, verbose_name='Фамилия')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('number', models.ManyToManyField(to='webduty.Fakultet', verbose_name='Факультет')),
                ('rank', models.ManyToManyField(max_length=30, related_name='Звание', to='webduty.Rank')),
            ],
            options={
                'verbose_name': 'Офицер',
                'verbose_name_plural': 'Офицеры',
            },
        ),
    ]
